export const LEVELS = {
  beginner: {
    id: "beginner",
    label: "مبتدئ",
    subtitle: "أسئلة سهلة وسريعة لبناء الثقة",
    total: 10,
    seconds: 25,
    pool: "beginner",
    accent: "#20c997",
  },
  intermediate: {
    id: "intermediate",
    label: "متوسط",
    subtitle: "اختبار متوازن في المفاهيم والتطبيق",
    total: 20,
    seconds: 30,
    pool: "intermediate",
    accent: "#18a9dc",
  },
  advanced: {
    id: "advanced",
    label: "متقدم",
    subtitle: "تحدي عميق للمتفوقين",
    total: 30,
    seconds: 40,
    pool: "advanced",
    accent: "#081b5f",
  },
};

export const CATEGORY_LABELS = {
  ai: "الذكاء الاصطناعي",
  robotics: "الروبوتيك",
  cs: "أساسيات المعلوميات",
  tech: "ثقافة التكنولوجيا",
};

const curatedQuestions = [
  {
    id: "b-ai-001",
    level: "beginner",
    category: "ai",
    type: "choice",
    visual: "ai",
    prompt: "ما المقصود بالذكاء الاصطناعي؟",
    options: [
      "برامج تحاول تنفيذ مهام تحتاج عادة إلى ذكاء بشري",
      "طريقة لتسريع شحن الهاتف فقط",
      "نوع من الطابعات ثلاثية الأبعاد",
      "لغة برمجة خاصة بالروبوتات فقط",
    ],
    answer: "برامج تحاول تنفيذ مهام تحتاج عادة إلى ذكاء بشري",
    explanation: "الذكاء الاصطناعي يجعل الأنظمة تتعرف، تتعلم، تتنبأ، أو تقرر في مهام تشبه بعض قدرات الإنسان.",
  },
  {
    id: "b-ai-002",
    level: "beginner",
    category: "ai",
    type: "boolean",
    visual: "ai",
    prompt: "نماذج مثل ChatGPT يمكنها توليد نصوص بناء على طلب المستخدم.",
    answer: true,
    explanation: "النماذج اللغوية الحديثة قادرة على فهم التعليمات وتوليد أجوبة نصية.",
  },
  {
    id: "b-ai-003",
    level: "beginner",
    category: "ai",
    type: "choice",
    visual: "data",
    prompt: "أي مثال يعتبر استخداما للذكاء الاصطناعي؟",
    options: [
      "تطبيق يتعرف على الوجه في الصورة",
      "مصباح يعمل بزر عادي",
      "دفتر ورقي للملاحظات",
      "كابل شحن USB",
    ],
    answer: "تطبيق يتعرف على الوجه في الصورة",
    explanation: "التعرف على الصور والوجوه من أشهر تطبيقات الذكاء الاصطناعي.",
  },
  {
    id: "b-ai-004",
    level: "beginner",
    category: "ai",
    type: "choice",
    visual: "ai",
    prompt: "ما معنى كلمة Prompt عند استعمال أدوات الذكاء الاصطناعي؟",
    options: [
      "التعليمة أو الطلب الذي نكتبه للنموذج",
      "سرعة الإنترنت",
      "زر إطفاء الحاسوب",
      "حجم الشاشة",
    ],
    answer: "التعليمة أو الطلب الذي نكتبه للنموذج",
    explanation: "كلما كانت التعليمة واضحة، كانت النتيجة غالبا أفضل.",
  },
  {
    id: "b-ai-005",
    level: "beginner",
    category: "ai",
    type: "multi",
    visual: "ai",
    prompt: "اختر أداتين يمكن استعمالهما لتوليد محتوى بالذكاء الاصطناعي.",
    options: ["ChatGPT", "DALL-E", "HDMI", "BIOS"],
    answers: ["ChatGPT", "DALL-E"],
    explanation: "ChatGPT يولد النصوص، وDALL-E يولد الصور من الوصف.",
  },
  {
    id: "b-ai-006",
    level: "beginner",
    category: "ai",
    type: "choice",
    visual: "data",
    prompt: "ما الشيء الذي يحتاجه نموذج التعلم الآلي غالبا لكي يتعلم؟",
    options: ["بيانات", "مكبر صوت", "غطاء حاسوب", "كابل كهربائي فقط"],
    answer: "بيانات",
    explanation: "التعلم الآلي يعتمد على البيانات لاستخراج الأنماط.",
  },
  {
    id: "b-ai-007",
    level: "beginner",
    category: "ai",
    type: "boolean",
    visual: "ai",
    prompt: "كل جواب يعطيه الذكاء الاصطناعي يجب اعتباره صحيحا دائما.",
    answer: false,
    explanation: "أدوات الذكاء الاصطناعي قد تخطئ، لذلك يجب التحقق من المعلومات المهمة.",
  },
  {
    id: "b-ai-008",
    level: "beginner",
    category: "ai",
    type: "match",
    visual: "tools",
    prompt: "طابق كل استعمال مع الأداة المناسبة.",
    pairs: [
      { left: "كتابة نص أو تلخيص", right: "ChatGPT" },
      { left: "توليد صورة من وصف", right: "DALL-E" },
      { left: "تحليل جدول بيانات", right: "أداة تحليل بيانات" },
    ],
    explanation: "اختيار الأداة يبدأ من فهم نوع المخرج المطلوب: نص، صورة، أو تحليل.",
  },
  {
    id: "b-ai-009",
    level: "beginner",
    category: "ai",
    type: "choice",
    visual: "ai",
    prompt: "أي عبارة تساعد أكثر في الحصول على جواب جيد من نموذج ذكاء اصطناعي؟",
    options: [
      "اشرح لي الفرق بين AI وML في 5 نقاط مع مثال بسيط",
      "اكتب شي حاجة",
      "؟؟؟",
      "نعم",
    ],
    answer: "اشرح لي الفرق بين AI وML في 5 نقاط مع مثال بسيط",
    explanation: "التحديد في الطلب يجعل النموذج يفهم الهدف والشكل المطلوب.",
  },
  {
    id: "b-ai-010",
    level: "beginner",
    category: "ai",
    type: "choice",
    visual: "vision",
    prompt: "أي مجال يهتم بجعل الحاسوب يفهم الصور والفيديو؟",
    options: ["الرؤية الحاسوبية", "الطباعة", "تبريد المعالج", "تخزين الملفات"],
    answer: "الرؤية الحاسوبية",
    explanation: "الرؤية الحاسوبية فرع من الذكاء الاصطناعي لمعالجة وفهم المرئيات.",
  },
  {
    id: "b-robot-001",
    level: "beginner",
    category: "robotics",
    type: "choice",
    visual: "robot",
    prompt: "ما هو الروبوت؟",
    options: [
      "آلة يمكنها تنفيذ مهام معينة باستعمال حساسات وبرمجة",
      "كتاب إلكتروني فقط",
      "نوع من أنواع البطاريات",
      "شبكة اجتماعية",
    ],
    answer: "آلة يمكنها تنفيذ مهام معينة باستعمال حساسات وبرمجة",
    explanation: "الروبوت يجمع غالبا بين جسم ميكانيكي، إلكترونيات، وبرمجيات.",
  },
  {
    id: "b-robot-002",
    level: "beginner",
    category: "robotics",
    type: "choice",
    visual: "sensor",
    prompt: "أي قطعة تساعد الروبوت على قياس المسافة؟",
    options: ["حساس الموجات فوق الصوتية", "لوحة مفاتيح", "سماعة رأس", "قرص DVD"],
    answer: "حساس الموجات فوق الصوتية",
    explanation: "هذا الحساس يرسل موجة ويقيس زمن عودتها لتقدير المسافة.",
  },
  {
    id: "b-robot-003",
    level: "beginner",
    category: "robotics",
    type: "boolean",
    visual: "robot",
    prompt: "Arduino لوحة إلكترونية يمكن استعمالها للتحكم في حساسات ومحركات.",
    answer: true,
    explanation: "Arduino شائعة في مشاريع الروبوتيك التعليمية.",
  },
  {
    id: "b-robot-004",
    level: "beginner",
    category: "robotics",
    type: "choice",
    visual: "motor",
    prompt: "ما وظيفة المحرك في الروبوت؟",
    options: ["إنتاج الحركة", "تخزين الصور", "عرض الفيديو", "حماية كلمة المرور"],
    answer: "إنتاج الحركة",
    explanation: "المحركات تحول الطاقة الكهربائية إلى حركة ميكانيكية.",
  },
  {
    id: "b-robot-005",
    level: "beginner",
    category: "robotics",
    type: "multi",
    visual: "robot",
    prompt: "اختر مكونين أساسيين في روبوت بسيط.",
    options: ["حساس", "محرك", "غلاف كتاب", "قلم رصاص"],
    answers: ["حساس", "محرك"],
    explanation: "الحساس يدخل المعلومات، والمحرك ينفذ الحركة.",
  },
  {
    id: "b-robot-006",
    level: "beginner",
    category: "robotics",
    type: "choice",
    visual: "sensor",
    prompt: "ما فائدة الحساسات في الروبوت؟",
    options: [
      "جمع معلومات من البيئة",
      "تزيين الواجهة فقط",
      "زيادة حجم الروبوت",
      "تعويض البطارية دائما",
    ],
    answer: "جمع معلومات من البيئة",
    explanation: "الحساسات تجعل الروبوت يتفاعل مع محيطه.",
  },
  {
    id: "b-robot-007",
    level: "beginner",
    category: "robotics",
    type: "boolean",
    visual: "robot",
    prompt: "الروبوت لا يحتاج أي برمجة لكي يغير سلوكه.",
    answer: false,
    explanation: "السلوك الذكي أو الآلي يحتاج تعليمات وبرمجة أو نظام تحكم.",
  },
  {
    id: "b-robot-008",
    level: "beginner",
    category: "robotics",
    type: "order",
    visual: "robot",
    prompt: "رتب دورة عمل روبوت يتفادى العوائق.",
    options: ["قراءة الحساس", "تحليل المسافة", "توجيه المحرك"],
    correctOrder: ["قراءة الحساس", "تحليل المسافة", "توجيه المحرك"],
    explanation: "الروبوت يقرأ البيئة، يقرر، ثم ينفذ الحركة.",
  },
  {
    id: "b-cs-001",
    level: "beginner",
    category: "cs",
    type: "choice",
    visual: "code",
    prompt: "ما هو المتغير في البرمجة؟",
    options: [
      "اسم نخزن فيه قيمة يمكن استعمالها لاحقا",
      "نوع من الشاشة",
      "سلك للشحن",
      "برنامج مضاد للفيروسات",
    ],
    answer: "اسم نخزن فيه قيمة يمكن استعمالها لاحقا",
    explanation: "المتغير يسمح للبرنامج بحفظ القيم ومعالجتها.",
  },
  {
    id: "b-cs-002",
    level: "beginner",
    category: "cs",
    type: "choice",
    visual: "code",
    prompt: "أي بنية تستعمل لتكرار نفس التعليمات عدة مرات؟",
    options: ["حلقة Loop", "تعليق Comment", "صورة PNG", "منفذ USB"],
    answer: "حلقة Loop",
    explanation: "الحلقات مثل for وwhile تستعمل للتكرار.",
  },
  {
    id: "b-cs-003",
    level: "beginner",
    category: "cs",
    type: "boolean",
    visual: "code",
    prompt: "الخوارزمية هي خطوات منظمة لحل مشكلة.",
    answer: true,
    explanation: "الخوارزمية تصف طريقة الحل قبل أو أثناء البرمجة.",
  },
  {
    id: "b-cs-004",
    level: "beginner",
    category: "cs",
    type: "choice",
    visual: "web",
    prompt: "أي لغة تستعمل غالبا لبناء هيكل صفحة الويب؟",
    options: ["HTML", "Bluetooth", "SSD", "GPU"],
    answer: "HTML",
    explanation: "HTML تصف عناصر الصفحة مثل العناوين والأزرار والصور.",
  },
  {
    id: "b-cs-005",
    level: "beginner",
    category: "cs",
    type: "choice",
    visual: "web",
    prompt: "ما دور CSS في صفحة الويب؟",
    options: ["تنسيق الألوان والمسافات والشكل", "تخزين الكهرباء", "تشغيل المروحة", "ضغط الملفات فقط"],
    answer: "تنسيق الألوان والمسافات والشكل",
    explanation: "CSS مسؤولة عن الشكل البصري والتجاوب.",
  },
  {
    id: "b-cs-006",
    level: "beginner",
    category: "cs",
    type: "choice",
    visual: "code",
    prompt: "أي لغة تستعمل كثيرا لإضافة التفاعل في صفحات الويب؟",
    options: ["JavaScript", "JPEG", "BIOS", "HDMI"],
    answer: "JavaScript",
    explanation: "JavaScript تجعل الصفحة تستجيب للنقرات والمدخلات وتغير المحتوى.",
  },
  {
    id: "b-cs-007",
    level: "beginner",
    category: "cs",
    type: "multi",
    visual: "code",
    prompt: "اختر نوعين شائعين من البيانات في البرمجة.",
    options: ["Number", "String", "Mousepad", "Router"],
    answers: ["Number", "String"],
    explanation: "الأرقام والنصوص من أكثر أنواع البيانات استعمالا.",
  },
  {
    id: "b-cs-008",
    level: "beginner",
    category: "cs",
    type: "order",
    visual: "code",
    prompt: "رتب خطوات حل مسألة برمجية بسيطة.",
    options: ["فهم المطلوب", "كتابة الخوارزمية", "اختبار الحل"],
    correctOrder: ["فهم المطلوب", "كتابة الخوارزمية", "اختبار الحل"],
    explanation: "الفهم الجيد قبل الكود يقلل الأخطاء.",
  },
  {
    id: "b-tech-001",
    level: "beginner",
    category: "tech",
    type: "choice",
    visual: "tech",
    prompt: "ما معنى اختصار CPU؟",
    options: ["وحدة المعالجة المركزية", "بطاقة الذاكرة", "منفذ الشحن", "نظام التشغيل"],
    answer: "وحدة المعالجة المركزية",
    explanation: "CPU هي العقل الحسابي الرئيسي في الحاسوب.",
  },
  {
    id: "b-tech-002",
    level: "beginner",
    category: "tech",
    type: "choice",
    visual: "tech",
    prompt: "ما وظيفة نظام التشغيل؟",
    options: [
      "إدارة العتاد والبرامج وتسهيل استعمال الحاسوب",
      "تغيير لون الطاولة",
      "قياس الحرارة فقط",
      "منع استعمال الإنترنت دائما",
    ],
    answer: "إدارة العتاد والبرامج وتسهيل استعمال الحاسوب",
    explanation: "Windows وLinux وmacOS أمثلة على أنظمة تشغيل.",
  },
  {
    id: "b-tech-003",
    level: "beginner",
    category: "tech",
    type: "boolean",
    visual: "security",
    prompt: "كلمة المرور القوية يفضل أن تكون طويلة ومتنوعة.",
    answer: true,
    explanation: "الطول والتنوع يصعبان تخمين كلمة المرور.",
  },
  {
    id: "b-tech-004",
    level: "beginner",
    category: "tech",
    type: "choice",
    visual: "network",
    prompt: "ما وظيفة الإنترنت؟",
    options: [
      "ربط أجهزة وشبكات حول العالم لتبادل المعلومات",
      "تنظيف شاشة الحاسوب",
      "زيادة وزن الهاتف",
      "تشغيل المصباح فقط",
    ],
    answer: "ربط أجهزة وشبكات حول العالم لتبادل المعلومات",
    explanation: "الإنترنت شبكة عالمية تربط خدمات ومستخدمين وأجهزة.",
  },
  {
    id: "b-tech-005",
    level: "beginner",
    category: "tech",
    type: "choice",
    visual: "security",
    prompt: "أي تصرف أفضل عند استقبال رابط مشبوه؟",
    options: [
      "عدم فتحه والتحقق من مصدره",
      "إرساله لكل الأصدقاء",
      "كتابة كلمة المرور فيه",
      "تحميل كل ملف فيه",
    ],
    answer: "عدم فتحه والتحقق من مصدره",
    explanation: "الحذر من الروابط المشبوهة يحمي من التصيد والبرمجيات الخبيثة.",
  },
  {
    id: "b-tech-006",
    level: "beginner",
    category: "tech",
    type: "choice",
    visual: "tech",
    prompt: "أي وحدة تستعمل عادة لقياس سعة التخزين؟",
    options: ["Gigabyte", "Volt", "Meter", "Second"],
    answer: "Gigabyte",
    explanation: "GB وTB وحدات شائعة للتخزين.",
  },
  {
    id: "b-tech-007",
    level: "beginner",
    category: "tech",
    type: "multi",
    visual: "security",
    prompt: "اختر ممارستين جيدتين للأمان الرقمي.",
    options: ["تفعيل التحقق بخطوتين", "تحديث البرامج", "استعمال نفس كلمة المرور دائما", "نشر كلمة المرور"],
    answers: ["تفعيل التحقق بخطوتين", "تحديث البرامج"],
    explanation: "التحديث والتحقق بخطوتين يقللان مخاطر الاختراق.",
  },
  {
    id: "b-tech-008",
    level: "beginner",
    category: "tech",
    type: "match",
    visual: "tech",
    prompt: "طابق المصطلح مع معناه.",
    pairs: [
      { left: "RAM", right: "ذاكرة مؤقتة أثناء التشغيل" },
      { left: "SSD", right: "وحدة تخزين سريعة" },
      { left: "GPU", right: "معالجة الرسوميات" },
    ],
    explanation: "هذه مكونات أساسية تؤثر في أداء الجهاز.",
  },
  {
    id: "i-ai-001",
    level: "intermediate",
    category: "ai",
    type: "choice",
    visual: "ai",
    prompt: "ما الفرق الأقرب للصواب بين الذكاء الاصطناعي والتعلم الآلي؟",
    options: [
      "التعلم الآلي فرع من الذكاء الاصطناعي يعتمد على تعلم الأنماط من البيانات",
      "الذكاء الاصطناعي هو الإنترنت فقط",
      "التعلم الآلي لا يستعمل البيانات",
      "هما نفس الشيء دائما بدون أي فرق",
    ],
    answer: "التعلم الآلي فرع من الذكاء الاصطناعي يعتمد على تعلم الأنماط من البيانات",
    explanation: "AI مفهوم أوسع، وML طريقة من طرق تحقيق بعض قدراته.",
  },
  {
    id: "i-ai-002",
    level: "intermediate",
    category: "ai",
    type: "choice",
    visual: "data",
    prompt: "في تدريب نموذج يصنف الرسائل إلى مزعجة وغير مزعجة، ماذا تمثل الرسائل المصنفة مسبقا؟",
    options: ["بيانات تدريب معنونة", "واجهة مستخدم", "محرك كهربائي", "نظام تشغيل"],
    answer: "بيانات تدريب معنونة",
    explanation: "وجود التصنيف الصحيح مع كل مثال يجعل التدريب موجها.",
  },
  {
    id: "i-ai-003",
    level: "intermediate",
    category: "ai",
    type: "boolean",
    visual: "data",
    prompt: "التحيز في البيانات قد يؤدي إلى قرارات غير عادلة من نموذج الذكاء الاصطناعي.",
    answer: true,
    explanation: "النموذج يتعلم من البيانات، فإذا كانت منحازة قد يكرر هذا الانحياز.",
  },
  {
    id: "i-ai-004",
    level: "intermediate",
    category: "ai",
    type: "choice",
    visual: "vision",
    prompt: "أي مهمة تنتمي غالبا إلى معالجة اللغة الطبيعية NLP؟",
    options: ["تلخيص مقال طويل", "قياس حرارة المعالج", "تحريك عجلة", "ضغط ملف ZIP"],
    answer: "تلخيص مقال طويل",
    explanation: "NLP يهتم بفهم وتوليد اللغة البشرية.",
  },
  {
    id: "i-ai-005",
    level: "intermediate",
    category: "ai",
    type: "multi",
    visual: "ai",
    prompt: "اختر عاملين يحسنان جودة جواب نموذج لغوي.",
    options: ["تعليمة واضحة", "سياق كاف", "طلب غامض جدا", "معلومات متناقضة"],
    answers: ["تعليمة واضحة", "سياق كاف"],
    explanation: "وضوح الهدف والسياق يساعدان النموذج على إنتاج جواب أدق.",
  },
  {
    id: "i-ai-006",
    level: "intermediate",
    category: "ai",
    type: "choice",
    visual: "ai",
    prompt: "ماذا يعني Fine-tuning بشكل مبسط؟",
    options: [
      "تكييف نموذج مدرب مسبقا على بيانات خاصة بمهمة محددة",
      "حذف كل بيانات التدريب",
      "تغيير لون واجهة التطبيق",
      "إيقاف النموذج نهائيا",
    ],
    answer: "تكييف نموذج مدرب مسبقا على بيانات خاصة بمهمة محددة",
    explanation: "الضبط الدقيق يجعل النموذج أقرب لمجال أو أسلوب معين.",
  },
  {
    id: "i-ai-007",
    level: "intermediate",
    category: "ai",
    type: "choice",
    visual: "data",
    prompt: "ما المقصود ببيانات الاختبار Test Data؟",
    options: [
      "بيانات لا يستعملها النموذج في التدريب وتستخدم لتقييمه",
      "بيانات لحذف النموذج",
      "صور واجهة الموقع",
      "أسماء الملفات فقط",
    ],
    answer: "بيانات لا يستعملها النموذج في التدريب وتستخدم لتقييمه",
    explanation: "بيانات الاختبار تساعد على قياس قدرة النموذج على التعميم.",
  },
  {
    id: "i-ai-008",
    level: "intermediate",
    category: "ai",
    type: "order",
    visual: "data",
    prompt: "رتب مراحل مشروع تعلم آلي مبسط.",
    options: ["جمع البيانات", "تدريب النموذج", "تقييم النموذج", "استعمال النموذج"],
    correctOrder: ["جمع البيانات", "تدريب النموذج", "تقييم النموذج", "استعمال النموذج"],
    explanation: "المشروع يبدأ بالبيانات وينتهي باستعمال نموذج تم تقييمه.",
  },
  {
    id: "i-ai-009",
    level: "intermediate",
    category: "ai",
    type: "choice",
    visual: "vision",
    prompt: "في تصنيف الصور، ما معنى Label؟",
    options: ["اسم الفئة الصحيحة للصورة", "حجم الشاشة", "نوع البطارية", "عدد منافذ USB"],
    answer: "اسم الفئة الصحيحة للصورة",
    explanation: "مثلا صورة قطة قد تحمل الوسم: قطة.",
  },
  {
    id: "i-robot-001",
    level: "intermediate",
    category: "robotics",
    type: "choice",
    visual: "robot",
    prompt: "ما وظيفة المتحكم الدقيق Microcontroller في روبوت بسيط؟",
    options: [
      "قراءة المدخلات وتنفيذ البرنامج للتحكم في المخرجات",
      "عرض الأفلام فقط",
      "تخزين الماء",
      "رفع سرعة الإنترنت مباشرة",
    ],
    answer: "قراءة المدخلات وتنفيذ البرنامج للتحكم في المخرجات",
    explanation: "المتحكم هو مركز القرار في كثير من مشاريع الروبوتيك.",
  },
  {
    id: "i-robot-002",
    level: "intermediate",
    category: "robotics",
    type: "choice",
    visual: "motor",
    prompt: "أي محرك مناسب غالبا للتحكم الدقيق في الزاوية؟",
    options: ["Servo motor", "مصباح LED", "مكبر صوت", "مفتاح عادي"],
    answer: "Servo motor",
    explanation: "محرك السيرفو يستعمل كثيرا لتحديد زاوية معينة.",
  },
  {
    id: "i-robot-003",
    level: "intermediate",
    category: "robotics",
    type: "boolean",
    visual: "sensor",
    prompt: "حساس الضوء يمكن أن يساعد الروبوت على التمييز بين مكان مضاء ومكان مظلم.",
    answer: true,
    explanation: "حساسات الضوء تقيس شدة الإضاءة في البيئة.",
  },
  {
    id: "i-robot-004",
    level: "intermediate",
    category: "robotics",
    type: "multi",
    visual: "robot",
    prompt: "اختر عنصرين من عناصر حلقة التحكم المغلقة.",
    options: ["قياس بالحساس", "تصحيح القرار حسب القياس", "تجاهل كل المدخلات", "إزالة المتحكم"],
    answers: ["قياس بالحساس", "تصحيح القرار حسب القياس"],
    explanation: "حلقة التحكم تقارن الحالة المطلوبة بالحالة المقاسة ثم تصحح.",
  },
  {
    id: "i-robot-005",
    level: "intermediate",
    category: "robotics",
    type: "choice",
    visual: "sensor",
    prompt: "لماذا لا نوصل محركا قويا مباشرة بمنفذ متحكم صغير غالبا؟",
    options: [
      "لأن المحرك قد يحتاج تيارا أكبر من قدرة المنفذ",
      "لأن المنفذ لا يعرف الألوان",
      "لأن المحرك يخزن الملفات",
      "لأن المتحكم لا يعمل إلا بدون كهرباء",
    ],
    answer: "لأن المحرك قد يحتاج تيارا أكبر من قدرة المنفذ",
    explanation: "غالبا نستعمل Driver أو ترانزستور لحماية المتحكم وتوفير التيار.",
  },
  {
    id: "i-robot-006",
    level: "intermediate",
    category: "robotics",
    type: "order",
    visual: "robot",
    prompt: "رتب خطوات روبوت يتبع خطا أسود.",
    options: ["قراءة حساسات الخط", "تحديد الانحراف", "تعديل سرعة العجلات", "إعادة القراءة"],
    correctOrder: ["قراءة حساسات الخط", "تحديد الانحراف", "تعديل سرعة العجلات", "إعادة القراءة"],
    explanation: "التتبع يعتمد على قراءة مستمرة وتصحيح حركة العجلات.",
  },
  {
    id: "i-robot-007",
    level: "intermediate",
    category: "robotics",
    type: "choice",
    visual: "robot",
    prompt: "ما فائدة PWM في التحكم بالمحركات أو LED؟",
    options: [
      "التحكم في القدرة المتوسطة عبر نبضات سريعة",
      "تخزين كلمات المرور",
      "قياس سعة القرص",
      "إنشاء صفحة HTML",
    ],
    answer: "التحكم في القدرة المتوسطة عبر نبضات سريعة",
    explanation: "PWM يستعمل لتغيير السرعة أو السطوع بشكل فعال.",
  },
  {
    id: "i-robot-008",
    level: "intermediate",
    category: "robotics",
    type: "match",
    visual: "robot",
    prompt: "طابق المكون مع دوره في الروبوت.",
    pairs: [
      { left: "حساس", right: "إدخال معلومات من البيئة" },
      { left: "متحكم", right: "تنفيذ القرار" },
      { left: "محرك", right: "إخراج حركة" },
    ],
    explanation: "الروبوت يعمل بمنطق إدخال، معالجة، ثم إخراج.",
  },
  {
    id: "i-cs-001",
    level: "intermediate",
    category: "cs",
    type: "choice",
    visual: "code",
    prompt: "ما التعقيد الزمني للبحث الخطي في قائمة طولها n؟",
    options: ["O(n)", "O(1)", "O(log n)", "O(n²)"],
    answer: "O(n)",
    explanation: "في أسوأ حالة نفحص كل العناصر مرة واحدة.",
  },
  {
    id: "i-cs-002",
    level: "intermediate",
    category: "cs",
    type: "choice",
    visual: "code",
    prompt: "أي بنية بيانات تعمل بمبدأ First In First Out؟",
    options: ["Queue", "Stack", "Tree", "Graph"],
    answer: "Queue",
    explanation: "الطابور Queue يخرج منه أول عنصر دخل أولا.",
  },
  {
    id: "i-cs-003",
    level: "intermediate",
    category: "cs",
    type: "choice",
    visual: "code",
    prompt: "أي بنية بيانات تعمل بمبدأ Last In First Out؟",
    options: ["Stack", "Queue", "Array", "Map"],
    answer: "Stack",
    explanation: "المكدس Stack يخرج منه آخر عنصر دخل أولا.",
  },
  {
    id: "i-cs-004",
    level: "intermediate",
    category: "cs",
    type: "boolean",
    visual: "code",
    prompt: "الدالة Function تساعد على تنظيم الكود وإعادة استعماله.",
    answer: true,
    explanation: "الدوال تقلل التكرار وتقسم البرنامج إلى أجزاء واضحة.",
  },
  {
    id: "i-cs-005",
    level: "intermediate",
    category: "cs",
    type: "choice",
    visual: "web",
    prompt: "في الويب، ماذا يفعل HTTP بشكل عام؟",
    options: [
      "ينظم تبادل الطلبات والردود بين المتصفح والخادم",
      "يشغل المروحة",
      "يرسم الصور فقط",
      "يقيس سرعة المعالج",
    ],
    answer: "ينظم تبادل الطلبات والردود بين المتصفح والخادم",
    explanation: "HTTP هو بروتوكول أساسي في تصفح الويب.",
  },
  {
    id: "i-cs-006",
    level: "intermediate",
    category: "cs",
    type: "multi",
    visual: "code",
    prompt: "اختر طريقتين لتحسين قابلية قراءة الكود.",
    options: ["أسماء واضحة", "تقسيم منطقي للدوال", "حذف كل المسافات", "كتابة كل شيء في سطر واحد"],
    answers: ["أسماء واضحة", "تقسيم منطقي للدوال"],
    explanation: "الكود الجيد يقرأه البشر بسهولة قبل أن ينفذه الحاسوب.",
  },
  {
    id: "i-cs-007",
    level: "intermediate",
    category: "cs",
    type: "order",
    visual: "code",
    prompt: "رتب خطوات البحث الثنائي Binary Search.",
    options: ["اختيار العنصر الأوسط", "مقارنة القيمة المطلوبة", "تجاهل نصف غير مناسب", "تكرار العملية"],
    correctOrder: ["اختيار العنصر الأوسط", "مقارنة القيمة المطلوبة", "تجاهل نصف غير مناسب", "تكرار العملية"],
    explanation: "البحث الثنائي يحتاج قائمة مرتبة ويقلص المجال كل مرة.",
  },
  {
    id: "i-cs-008",
    level: "intermediate",
    category: "cs",
    type: "choice",
    visual: "code",
    prompt: "ما أفضل وصف للـ API؟",
    options: [
      "واجهة تسمح لبرامج مختلفة بالتواصل وفق قواعد محددة",
      "نوع من الكراسي",
      "بطارية صغيرة",
      "لون في CSS فقط",
    ],
    answer: "واجهة تسمح لبرامج مختلفة بالتواصل وفق قواعد محددة",
    explanation: "API يحدد كيف يطلب برنامج خدمة أو بيانات من برنامج آخر.",
  },
  {
    id: "i-tech-001",
    level: "intermediate",
    category: "tech",
    type: "choice",
    visual: "security",
    prompt: "ما المقصود بالتصيد Phishing؟",
    options: [
      "خداع المستخدم للحصول على معلوماته الحساسة",
      "تحسين جودة الصورة",
      "تنظيف الذاكرة المؤقتة",
      "رفع دقة الشاشة",
    ],
    answer: "خداع المستخدم للحصول على معلوماته الحساسة",
    explanation: "التصيد يستعمل رسائل أو صفحات مزيفة لسرقة الحسابات أو البيانات.",
  },
  {
    id: "i-tech-002",
    level: "intermediate",
    category: "tech",
    type: "choice",
    visual: "network",
    prompt: "ما وظيفة DNS في الإنترنت؟",
    options: [
      "تحويل أسماء المواقع إلى عناوين IP",
      "تشغيل لوحة المفاتيح",
      "زيادة سعة البطارية",
      "تغيير لون الصفحة",
    ],
    answer: "تحويل أسماء المواقع إلى عناوين IP",
    explanation: "DNS يجعلنا نستعمل أسماء سهلة بدل تذكر عناوين رقمية.",
  },
  {
    id: "i-tech-003",
    level: "intermediate",
    category: "tech",
    type: "boolean",
    visual: "security",
    prompt: "التحديثات الأمنية قد تصلح ثغرات يمكن استغلالها.",
    answer: true,
    explanation: "إهمال التحديثات يترك الجهاز معرضا لمشاكل معروفة.",
  },
  {
    id: "i-tech-004",
    level: "intermediate",
    category: "tech",
    type: "multi",
    visual: "network",
    prompt: "اختر مثالين على خدمات سحابية.",
    options: ["تخزين ملفات على الإنترنت", "تشغيل تطبيقات على خوادم بعيدة", "كابل HDMI", "ممحاة ورقية"],
    answers: ["تخزين ملفات على الإنترنت", "تشغيل تطبيقات على خوادم بعيدة"],
    explanation: "السحابة توفر موارد وخدمات عبر الإنترنت.",
  },
  {
    id: "i-tech-005",
    level: "intermediate",
    category: "tech",
    type: "choice",
    visual: "security",
    prompt: "ماذا تعني المصادقة الثنائية 2FA؟",
    options: [
      "استعمال عامل تحقق إضافي بجانب كلمة المرور",
      "فتح حسابين بنفس الاسم",
      "تغيير الشاشة مرتين",
      "حذف كلمة المرور نهائيا",
    ],
    answer: "استعمال عامل تحقق إضافي بجانب كلمة المرور",
    explanation: "2FA تضيف طبقة حماية مثل رمز من الهاتف أو تطبيق مصادقة.",
  },
  {
    id: "i-tech-006",
    level: "intermediate",
    category: "tech",
    type: "match",
    visual: "tech",
    prompt: "طابق التقنية مع الاستخدام الأقرب.",
    pairs: [
      { left: "Bluetooth", right: "اتصال قصير المدى" },
      { left: "Cloud", right: "موارد عبر الإنترنت" },
      { left: "Encryption", right: "حماية البيانات بالتشفير" },
    ],
    explanation: "كل تقنية لها دور واضح في الاتصال أو الحماية أو توفير الموارد.",
  },
  {
    id: "i-tech-007",
    level: "intermediate",
    category: "tech",
    type: "choice",
    visual: "network",
    prompt: "ما المقصود بعنوان IP؟",
    options: [
      "عنوان رقمي يميز جهازا أو خدمة داخل شبكة",
      "اسم لون في التصميم",
      "نوع من المعالجات",
      "ملف صوتي",
    ],
    answer: "عنوان رقمي يميز جهازا أو خدمة داخل شبكة",
    explanation: "الأجهزة تستعمل عناوين IP للتواصل عبر الشبكات.",
  },
  {
    id: "i-tech-008",
    level: "intermediate",
    category: "tech",
    type: "choice",
    visual: "tech",
    prompt: "أي وصف مناسب لمفهوم Open Source؟",
    options: [
      "برمجيات يمكن الاطلاع على كودها وغالبا تعديلها وفق رخصتها",
      "برنامج بدون أي كود",
      "جهاز لا يحتاج كهرباء",
      "نوع من شاشات اللمس فقط",
    ],
    answer: "برمجيات يمكن الاطلاع على كودها وغالبا تعديلها وفق رخصتها",
    explanation: "المصدر المفتوح يشجع الشفافية والتعاون وفق شروط الرخصة.",
  },
  {
    id: "a-ai-001",
    level: "advanced",
    category: "ai",
    type: "choice",
    visual: "ai",
    prompt: "في نماذج اللغة الكبيرة، ما المقصود غالبا بالـ Context Window؟",
    options: [
      "حجم النص الذي يستطيع النموذج أخذه بعين الاعتبار في طلب واحد",
      "حجم شاشة الحاسوب",
      "عدد ألوان الصورة",
      "سرعة المعالج فقط",
    ],
    answer: "حجم النص الذي يستطيع النموذج أخذه بعين الاعتبار في طلب واحد",
    explanation: "نافذة السياق تحدد مقدار التعليمات والمحادثة والوثائق التي يمكن للنموذج قراءتها معا.",
  },
  {
    id: "a-ai-002",
    level: "advanced",
    category: "ai",
    type: "choice",
    visual: "data",
    prompt: "ما الهدف الأساسي من Regularization في التعلم الآلي؟",
    options: [
      "تقليل فرط التكيف Overfitting وتحسين التعميم",
      "زيادة حجم الشاشة",
      "حذف بيانات الاختبار",
      "إلغاء الحاجة إلى البيانات",
    ],
    answer: "تقليل فرط التكيف Overfitting وتحسين التعميم",
    explanation: "Regularization تضيف قيودا أو عقوبات لتجنب تعلم تفاصيل ضيقة من بيانات التدريب.",
  },
  {
    id: "a-ai-003",
    level: "advanced",
    category: "ai",
    type: "boolean",
    visual: "data",
    prompt: "ارتفاع الدقة Accuracy دائما كاف لتقييم نموذج على بيانات غير متوازنة.",
    answer: false,
    explanation: "مع البيانات غير المتوازنة نحتاج مقاييس مثل Precision وRecall وF1.",
  },
  {
    id: "a-ai-004",
    level: "advanced",
    category: "ai",
    type: "multi",
    visual: "ai",
    prompt: "اختر مقياسين مناسبين لتقييم نموذج تصنيف ثنائي.",
    options: ["Precision", "Recall", "لون الواجهة", "حجم الخط"],
    answers: ["Precision", "Recall"],
    explanation: "Precision وRecall يكشفان جودة النموذج خصوصا عندما تكون الفئات غير متوازنة.",
  },
  {
    id: "a-ai-005",
    level: "advanced",
    category: "ai",
    type: "choice",
    visual: "ai",
    prompt: "ما الفكرة العامة وراء RAG في تطبيقات الذكاء الاصطناعي؟",
    options: [
      "جلب معلومات من مصادر خارجية ثم استعمالها لتوليد جواب أدق",
      "إيقاف النموذج عن القراءة",
      "تغيير خط النص فقط",
      "تقليل عدد المستخدمين",
    ],
    answer: "جلب معلومات من مصادر خارجية ثم استعمالها لتوليد جواب أدق",
    explanation: "RAG يجمع بين الاسترجاع من قاعدة معرفة والتوليد بواسطة نموذج لغوي.",
  },
  {
    id: "a-ai-006",
    level: "advanced",
    category: "ai",
    type: "order",
    visual: "data",
    prompt: "رتب مسار بناء نظام RAG مبسط.",
    options: ["تقسيم الوثائق", "إنشاء Embeddings", "استرجاع المقاطع المناسبة", "توليد الجواب بالسياق"],
    correctOrder: ["تقسيم الوثائق", "إنشاء Embeddings", "استرجاع المقاطع المناسبة", "توليد الجواب بالسياق"],
    explanation: "النظام يسترجع السياق المناسب قبل أن يطلب من النموذج توليد الجواب.",
  },
  {
    id: "a-ai-007",
    level: "advanced",
    category: "ai",
    type: "choice",
    visual: "data",
    prompt: "ما المقصود بـ Embedding في تطبيقات الذكاء الاصطناعي؟",
    options: [
      "تمثيل رقمي للنص أو الصورة يحافظ على المعنى نسبيا",
      "كابل يربط الشاشة",
      "صيغة ضغط صوتية",
      "قطعة لتبريد المعالج",
    ],
    answer: "تمثيل رقمي للنص أو الصورة يحافظ على المعنى نسبيا",
    explanation: "Embeddings تسهل البحث الدلالي والمقارنة بين المعاني.",
  },
  {
    id: "a-ai-008",
    level: "advanced",
    category: "ai",
    type: "choice",
    visual: "ai",
    prompt: "في Prompt Engineering، لماذا نستعمل أمثلة Few-shot؟",
    options: [
      "لإظهار نمط الإجابة المطلوب للنموذج عبر أمثلة قليلة",
      "لتقليل وضوح الطلب",
      "لحذف السياق",
      "لتغيير سرعة الإنترنت",
    ],
    answer: "لإظهار نمط الإجابة المطلوب للنموذج عبر أمثلة قليلة",
    explanation: "الأمثلة تساعد النموذج على اتباع تنسيق ومنطق معين.",
  },
  {
    id: "a-ai-009",
    level: "advanced",
    category: "ai",
    type: "match",
    visual: "ai",
    prompt: "طابق المفهوم مع وصفه الأقرب.",
    pairs: [
      { left: "Overfitting", right: "حفظ تفاصيل التدريب بدل التعميم" },
      { left: "Inference", right: "استعمال النموذج لإنتاج نتيجة" },
      { left: "Dataset Split", right: "تقسيم البيانات للتدريب والتقييم" },
    ],
    explanation: "هذه مفاهيم محورية في بناء وتقييم نماذج الذكاء الاصطناعي.",
  },
  {
    id: "a-robot-001",
    level: "advanced",
    category: "robotics",
    type: "choice",
    visual: "robot",
    prompt: "ما دور PID Controller في التحكم؟",
    options: [
      "تقليل الخطأ بين القيمة المطلوبة والقيمة المقاسة باستعمال حدود P وI وD",
      "تشفير كلمة المرور",
      "تغيير لون الهيكل",
      "ضغط الصور فقط",
    ],
    answer: "تقليل الخطأ بين القيمة المطلوبة والقيمة المقاسة باستعمال حدود P وI وD",
    explanation: "PID من أشهر خوارزميات التحكم في الأنظمة الفيزيائية.",
  },
  {
    id: "a-robot-002",
    level: "advanced",
    category: "robotics",
    type: "choice",
    visual: "sensor",
    prompt: "ما المقصود بـ Sensor Fusion؟",
    options: [
      "دمج قراءات عدة حساسات للحصول على تقدير أفضل للحالة",
      "إلغاء كل الحساسات",
      "توصيل المحرك مباشرة بالكاميرا",
      "تغيير لون الأسلاك",
    ],
    answer: "دمج قراءات عدة حساسات للحصول على تقدير أفضل للحالة",
    explanation: "دمج الحساسات يقلل الضجيج ويعطي رؤية أشمل للبيئة.",
  },
  {
    id: "a-robot-003",
    level: "advanced",
    category: "robotics",
    type: "boolean",
    visual: "robot",
    prompt: "في نظام تحكم مغلق، قياس الخرج يستعمل لتصحيح القرار القادم.",
    answer: true,
    explanation: "هذه هي فكرة Feedback في التحكم.",
  },
  {
    id: "a-robot-004",
    level: "advanced",
    category: "robotics",
    type: "multi",
    visual: "robot",
    prompt: "اختر عاملين مهمين عند تصميم روبوت متنقل.",
    options: ["استهلاك الطاقة", "ثبات الحركة", "لون الملصق فقط", "اسم الملف"],
    answers: ["استهلاك الطاقة", "ثبات الحركة"],
    explanation: "الطاقة والثبات يؤثران مباشرة على مدة العمل وجودة التنقل.",
  },
  {
    id: "a-robot-005",
    level: "advanced",
    category: "robotics",
    type: "choice",
    visual: "robot",
    prompt: "متى يكون استعمال Odometry مفيدا؟",
    options: [
      "لتقدير حركة الروبوت وموقعه من دوران العجلات أو الحساسات",
      "لتغيير كلمة المرور",
      "لتوليد صور فنية",
      "لتنظيف قاعدة البيانات",
    ],
    answer: "لتقدير حركة الروبوت وموقعه من دوران العجلات أو الحساسات",
    explanation: "Odometry مفيد لكنه قد يتراكم فيه الخطأ مع الوقت.",
  },
  {
    id: "a-robot-006",
    level: "advanced",
    category: "robotics",
    type: "order",
    visual: "robot",
    prompt: "رتب حلقة تحكم PID مبسطة.",
    options: ["قياس القيمة الحالية", "حساب الخطأ", "حساب إشارة التحكم", "تطبيق الإشارة على المحرك"],
    correctOrder: ["قياس القيمة الحالية", "حساب الخطأ", "حساب إشارة التحكم", "تطبيق الإشارة على المحرك"],
    explanation: "كل دورة تحكم تبدأ بقياس ثم تصحيح بناء على الخطأ.",
  },
  {
    id: "a-robot-007",
    level: "advanced",
    category: "robotics",
    type: "choice",
    visual: "sensor",
    prompt: "ما تحدي استعمال الكاميرا في روبوت حقيقي؟",
    options: [
      "تحتاج معالجة بيانات كثيرة وتتأثر بالإضاءة",
      "لا تنتج أي بيانات",
      "تعمل فقط بدون كهرباء",
      "تمنع استعمال المتحكم",
    ],
    answer: "تحتاج معالجة بيانات كثيرة وتتأثر بالإضاءة",
    explanation: "الرؤية مفيدة لكنها تحتاج قدرة معالجة وخوارزميات قوية.",
  },
  {
    id: "a-robot-008",
    level: "advanced",
    category: "robotics",
    type: "match",
    visual: "robot",
    prompt: "طابق المفهوم مع استعماله.",
    pairs: [
      { left: "PID", right: "تحكم دقيق بالخطأ" },
      { left: "SLAM", right: "بناء خريطة وتحديد موقع" },
      { left: "IMU", right: "قياس التسارع والدوران" },
    ],
    explanation: "هذه مفاهيم تستعمل في روبوتات أكثر تقدما.",
  },
  {
    id: "a-cs-001",
    level: "advanced",
    category: "cs",
    type: "choice",
    visual: "code",
    prompt: "ما التعقيد الزمني للبحث الثنائي في قائمة مرتبة طولها n؟",
    options: ["O(log n)", "O(n)", "O(n²)", "O(1) دائما"],
    answer: "O(log n)",
    explanation: "كل خطوة تقسم مجال البحث إلى النصف.",
  },
  {
    id: "a-cs-002",
    level: "advanced",
    category: "cs",
    type: "choice",
    visual: "code",
    prompt: "أي بنية مناسبة لتمثيل علاقات كثيرة بين عناصر مثل المدن والطرق؟",
    options: ["Graph", "Stack فقط", "String", "Boolean"],
    answer: "Graph",
    explanation: "الرسم البياني يمثل العقد والروابط بينها.",
  },
  {
    id: "a-cs-003",
    level: "advanced",
    category: "cs",
    type: "boolean",
    visual: "code",
    prompt: "الخوارزمية ذات O(n²) قد تصبح بطيئة جدا عندما يكبر n.",
    answer: true,
    explanation: "النمو التربيعي يزيد عدد العمليات بسرعة كبيرة.",
  },
  {
    id: "a-cs-004",
    level: "advanced",
    category: "cs",
    type: "multi",
    visual: "code",
    prompt: "اختر مفهومين من مفاهيم البرمجة الكائنية OOP.",
    options: ["Encapsulation", "Inheritance", "Voltage", "Pixel Density"],
    answers: ["Encapsulation", "Inheritance"],
    explanation: "التغليف والوراثة من أعمدة OOP.",
  },
  {
    id: "a-cs-005",
    level: "advanced",
    category: "cs",
    type: "choice",
    visual: "code",
    prompt: "ما الفكرة الأساسية في Recursion؟",
    options: [
      "دالة تستدعي نفسها لحل أجزاء أصغر من المشكلة",
      "حذف كل الدوال",
      "تشغيل البرنامج بدون ذاكرة",
      "تغيير لون النص",
    ],
    answer: "دالة تستدعي نفسها لحل أجزاء أصغر من المشكلة",
    explanation: "Recursion تحتاج حالة توقف واضحة حتى لا تستمر بلا نهاية.",
  },
  {
    id: "a-cs-006",
    level: "advanced",
    category: "cs",
    type: "order",
    visual: "code",
    prompt: "رتب خطوات تصميم خوارزمية Dynamic Programming.",
    options: ["تحديد الحالات", "صياغة الانتقال", "تحديد القيم الابتدائية", "حساب النتيجة"],
    correctOrder: ["تحديد الحالات", "صياغة الانتقال", "تحديد القيم الابتدائية", "حساب النتيجة"],
    explanation: "البرمجة الديناميكية تعتمد على حالات وانتقالات وقيم ابتدائية.",
  },
  {
    id: "a-cs-007",
    level: "advanced",
    category: "cs",
    type: "choice",
    visual: "web",
    prompt: "لماذا نستعمل Git في المشاريع البرمجية؟",
    options: [
      "لتتبع التغييرات والتعاون والرجوع للإصدارات السابقة",
      "لتبريد المعالج",
      "لتوليد الكهرباء",
      "لتغيير دقة الشاشة",
    ],
    answer: "لتتبع التغييرات والتعاون والرجوع للإصدارات السابقة",
    explanation: "Git نظام تحكم في النسخ مهم للعمل الفردي والجماعي.",
  },
  {
    id: "a-cs-008",
    level: "advanced",
    category: "cs",
    type: "match",
    visual: "code",
    prompt: "طابق البنية مع الخاصية الأساسية.",
    pairs: [
      { left: "Hash Map", right: "وصول سريع بالمفتاح غالبا" },
      { left: "Tree", right: "علاقات هرمية" },
      { left: "Queue", right: "أول داخل أول خارج" },
    ],
    explanation: "اختيار بنية البيانات المناسبة يحسن الحل كثيرا.",
  },
  {
    id: "a-tech-001",
    level: "advanced",
    category: "tech",
    type: "choice",
    visual: "network",
    prompt: "ما الفرق العام بين التشفير المتماثل وغير المتماثل؟",
    options: [
      "المتماثل يستعمل مفتاحا واحدا غالبا، وغير المتماثل يستعمل زوج مفاتيح",
      "المتماثل لا يحمي البيانات أبدا",
      "غير المتماثل خاص بالصور فقط",
      "لا يوجد أي فرق",
    ],
    answer: "المتماثل يستعمل مفتاحا واحدا غالبا، وغير المتماثل يستعمل زوج مفاتيح",
    explanation: "التشفير غير المتماثل يستعمل مفتاحا عاما وآخر خاصا.",
  },
  {
    id: "a-tech-002",
    level: "advanced",
    category: "tech",
    type: "choice",
    visual: "network",
    prompt: "ما فائدة HTTPS مقارنة بـ HTTP؟",
    options: [
      "يوفر تشفيرا وتحققا أفضل أثناء الاتصال",
      "يجعل الشاشة أكبر",
      "يحذف الحاجة إلى المتصفح",
      "يمنع تحميل الصور دائما",
    ],
    answer: "يوفر تشفيرا وتحققا أفضل أثناء الاتصال",
    explanation: "HTTPS يحمي الاتصال باستعمال TLS.",
  },
  {
    id: "a-tech-003",
    level: "advanced",
    category: "tech",
    type: "boolean",
    visual: "security",
    prompt: "النسخ الاحتياطي المنتظم يقلل أثر فقدان البيانات أو هجوم الفدية.",
    answer: true,
    explanation: "Backups الجيدة تجعل الاسترجاع ممكنا بعد الحوادث.",
  },
  {
    id: "a-tech-004",
    level: "advanced",
    category: "tech",
    type: "multi",
    visual: "security",
    prompt: "اختر إجراءين لتقليل مخاطر اختراق حساب مهم.",
    options: ["استعمال مدير كلمات مرور", "تفعيل 2FA", "إعادة استعمال نفس كلمة المرور", "مشاركة الرمز مع الغرباء"],
    answers: ["استعمال مدير كلمات مرور", "تفعيل 2FA"],
    explanation: "مدير كلمات المرور و2FA يرفعان مستوى الحماية بشكل عملي.",
  },
  {
    id: "a-tech-005",
    level: "advanced",
    category: "tech",
    type: "choice",
    visual: "network",
    prompt: "ما المقصود بالحاويات Containers في البرمجيات؟",
    options: [
      "طريقة لتشغيل تطبيق مع اعتمادياته في بيئة معزولة نسبيا",
      "حافظة ملفات ورقية",
      "كابل للشاشة",
      "لوحة مفاتيح افتراضية فقط",
    ],
    answer: "طريقة لتشغيل تطبيق مع اعتمادياته في بيئة معزولة نسبيا",
    explanation: "Containers تساعد على نقل وتشغيل التطبيقات بشكل متوقع.",
  },
  {
    id: "a-tech-006",
    level: "advanced",
    category: "tech",
    type: "order",
    visual: "security",
    prompt: "رتب استجابة أولية لحادث أمني بسيط.",
    options: ["عزل الجهاز أو الحساب المتأثر", "تغيير كلمات المرور", "مراجعة السجلات", "تحديث الإجراءات لمنع التكرار"],
    correctOrder: ["عزل الجهاز أو الحساب المتأثر", "تغيير كلمات المرور", "مراجعة السجلات", "تحديث الإجراءات لمنع التكرار"],
    explanation: "الاستجابة تبدأ بتقليل الضرر ثم الفهم والتحسين.",
  },
  {
    id: "a-tech-007",
    level: "advanced",
    category: "tech",
    type: "choice",
    visual: "network",
    prompt: "ما وظيفة Load Balancer في الأنظمة الخدمية؟",
    options: [
      "توزيع الطلبات على عدة خوادم لتحسين الاعتمادية والأداء",
      "تلوين الصفحة تلقائيا",
      "ضغط الصور في الهاتف",
      "حذف قواعد البيانات",
    ],
    answer: "توزيع الطلبات على عدة خوادم لتحسين الاعتمادية والأداء",
    explanation: "موازن الحمل يساعد على تحمل عدد أكبر من الطلبات وتقليل نقطة الفشل الواحدة.",
  },
  {
    id: "a-tech-008",
    level: "advanced",
    category: "tech",
    type: "match",
    visual: "network",
    prompt: "طابق المفهوم مع الوصف.",
    pairs: [
      { left: "Firewall", right: "فلترة حركة الشبكة" },
      { left: "TLS", right: "تأمين الاتصال" },
      { left: "Backup", right: "نسخة قابلة للاسترجاع" },
    ],
    explanation: "هذه مفاهيم أساسية في أمن وتشغيل الأنظمة.",
  },
];

const categoryQuestionContext = {
  ai: {
    arDomain: "الذكاء الاصطناعي",
    frDomain: "l'intelligence artificielle",
    arConceptKind: "مفهوم",
    frConceptKind: "un concept",
    arOffTopic: "اختيار لون خلفية التطبيق فقط",
    frOffTopic: "choisir seulement la couleur de fond de l'application",
    arWorkflow: ["تحديد المهمة", "جمع أمثلة أو بيانات مناسبة", "اختيار الأداة أو النموذج", "اختبار النتيجة والتحقق منها"],
    frWorkflow: ["Définir la tâche", "Rassembler des exemples ou des données", "Choisir l'outil ou le modèle", "Tester et vérifier le résultat"],
  },
  robotics: {
    arDomain: "الروبوتيك",
    frDomain: "la robotique",
    arConceptKind: "مكون أو مفهوم",
    frConceptKind: "un composant ou un concept",
    arOffTopic: "تغيير لون هيكل الروبوت فقط",
    frOffTopic: "changer seulement la couleur du robot",
    arWorkflow: ["تحديد السلوك المطلوب", "اختيار الحساسات والمحركات", "كتابة برنامج التحكم", "اختبار الروبوت بأمان"],
    frWorkflow: ["Définir le comportement attendu", "Choisir les capteurs et moteurs", "Écrire le programme de contrôle", "Tester le robot en sécurité"],
  },
  cs: {
    arDomain: "المعلوميات",
    frDomain: "l'informatique",
    arConceptKind: "مفهوم",
    frConceptKind: "un concept",
    arOffTopic: "تزيين النص دون حل المشكلة",
    frOffTopic: "décorer le texte sans résoudre le problème",
    arWorkflow: ["فهم المسألة", "تصميم الخوارزمية", "كتابة الحل", "اختبار الحالات المهمة"],
    frWorkflow: ["Comprendre le problème", "Concevoir l'algorithme", "Coder la solution", "Tester les cas importants"],
  },
  tech: {
    arDomain: "الثقافة التقنية",
    frDomain: "la culture technologique",
    arConceptKind: "مفهوم أو تقنية",
    frConceptKind: "un concept ou une technologie",
    arOffTopic: "زيادة سطوع الشاشة فقط",
    frOffTopic: "augmenter seulement la luminosité de l'écran",
    arWorkflow: ["تحديد الحاجة", "اختيار التقنية المناسبة", "تطبيق الإعدادات", "مراقبة الأمان والأداء"],
    frWorkflow: ["Identifier le besoin", "Choisir la technologie adaptée", "Appliquer la configuration", "Surveiller la sécurité et la performance"],
  },
};

const questionExpansionSeeds = [
  ["beginner", "ai", "ai", "التعلم الآلي", "l'apprentissage automatique", "تعلم أنماط من البيانات", "apprendre des régularités à partir des données"],
  ["beginner", "ai", "data", "البيانات التدريبية", "les données d'entraînement", "تدريب نموذج على أمثلة صحيحة", "entraîner un modèle avec des exemples corrects"],
  ["beginner", "ai", "ai", "Prompt واضح", "un prompt clair", "توجيه نموذج الذكاء الاصطناعي", "guider un modèle d'IA"],
  ["beginner", "ai", "tools", "نماذج اللغة", "les modèles de langage", "فهم وكتابة النصوص", "comprendre et produire du texte"],
  ["beginner", "ai", "vision", "توليد الصور", "la génération d'images", "إنشاء صورة من وصف مكتوب", "créer une image depuis une description"],
  ["beginner", "ai", "vision", "التعرف على الصور", "la reconnaissance d'images", "اكتشاف عناصر داخل صورة", "détecter des éléments dans une image"],
  ["beginner", "ai", "tools", "التحقق من جواب الذكاء الاصطناعي", "la vérification d'une réponse d'IA", "تجنب قبول معلومات خاطئة", "éviter d'accepter une information fausse"],
  ["beginner", "ai", "data", "التصنيف البسيط", "la classification simple", "وضع مثال داخل فئة مناسبة", "placer un exemple dans la bonne catégorie"],
  ["intermediate", "ai", "data", "بيانات التدريب والاختبار", "les données d'entraînement et de test", "قياس أداء النموذج على أمثلة جديدة", "mesurer le modèle sur de nouveaux exemples"],
  ["intermediate", "ai", "ai", "التحيز في البيانات", "le biais dans les données", "فهم سبب قرارات غير عادلة", "comprendre les décisions injustes"],
  ["intermediate", "ai", "ai", "معالجة اللغة الطبيعية", "le traitement du langage naturel", "تحليل النصوص والأسئلة", "analyser les textes et les questions"],
  ["intermediate", "ai", "data", "تقييم النموذج", "l'évaluation du modèle", "معرفة هل النموذج يعمل جيدا", "savoir si le modèle fonctionne bien"],
  ["intermediate", "ai", "ai", "Fine-tuning", "le fine-tuning", "تكييف نموذج على مجال محدد", "adapter un modèle à un domaine précis"],
  ["intermediate", "ai", "tools", "اختيار أداة الذكاء الاصطناعي", "le choix d'un outil d'IA", "مطابقة المهمة مع الأداة المناسبة", "associer la tâche au bon outil"],
  ["intermediate", "ai", "data", "تنظيف البيانات", "le nettoyage des données", "إزالة الأخطاء قبل التحليل", "retirer les erreurs avant l'analyse"],
  ["intermediate", "ai", "vision", "Computer Vision", "la vision par ordinateur", "تحليل الصور والفيديو", "analyser les images et les vidéos"],
  ["advanced", "ai", "ai", "RAG", "le RAG", "ربط النموذج بمصادر معرفة موثوقة", "relier le modèle à des sources fiables"],
  ["advanced", "ai", "data", "Embedding", "l'embedding", "تمثيل المعنى بأرقام قابلة للمقارنة", "représenter le sens avec des nombres comparables"],
  ["advanced", "ai", "ai", "Context Window", "la fenêtre de contexte", "تحديد كمية النص التي يراها النموذج", "limiter la quantité de texte visible par le modèle"],
  ["advanced", "ai", "data", "Overfitting", "le surapprentissage", "فهم لماذا يحفظ النموذج التدريب بدل التعميم", "comprendre pourquoi un modèle mémorise au lieu de généraliser"],
  ["advanced", "ai", "data", "Precision و Recall", "la précision et le rappel", "تقييم التصنيف عندما تكون البيانات غير متوازنة", "évaluer une classification avec des données déséquilibrées"],
  ["advanced", "ai", "data", "Vector Database", "la base vectorielle", "البحث عن نصوص قريبة في المعنى", "rechercher des textes proches par le sens"],
  ["advanced", "ai", "tools", "AI Agent", "l'agent IA", "تنفيذ خطوات متعددة باستعمال أدوات", "exécuter plusieurs étapes avec des outils"],
  ["advanced", "ai", "security", "سلامة النماذج", "la sûreté des modèles", "تقليل الإجابات الخطيرة أو المضللة", "réduire les réponses dangereuses ou trompeuses"],
  ["advanced", "ai", "tools", "Prompt Few-shot", "le prompt few-shot", "تعليم النموذج بأمثلة قليلة داخل الطلب", "guider le modèle avec quelques exemples dans la consigne"],

  ["beginner", "robotics", "robot", "الروبوت", "le robot", "تنفيذ مهام آلية في العالم الحقيقي", "réaliser des tâches automatiques dans le monde réel"],
  ["beginner", "robotics", "sensor", "الحساس", "le capteur", "قراءة معلومات من المحيط", "lire des informations de l'environnement"],
  ["beginner", "robotics", "motor", "المحرك", "le moteur", "تحويل الطاقة إلى حركة", "transformer l'énergie en mouvement"],
  ["beginner", "robotics", "robot", "Arduino", "Arduino", "التحكم في حساسات ومحركات تعليمية", "contrôler des capteurs et moteurs éducatifs"],
  ["beginner", "robotics", "robot", "LED", "la LED", "إظهار حالة كهربائية أو نتيجة بسيطة", "afficher un état électrique ou un résultat simple"],
  ["beginner", "robotics", "motor", "Servo Motor", "le servomoteur", "تحريك جزء بزاوية محددة", "déplacer une pièce avec un angle précis"],
  ["beginner", "robotics", "sensor", "حساس الموجات فوق الصوتية", "le capteur ultrason", "قياس المسافة إلى عائق", "mesurer la distance jusqu'à un obstacle"],
  ["beginner", "robotics", "robot", "مصدر الطاقة", "la source d'énergie", "تشغيل الدارة والمحركات", "alimenter le circuit et les moteurs"],
  ["intermediate", "robotics", "motor", "PWM", "le PWM", "التحكم في السرعة أو شدة الإضاءة", "contrôler la vitesse ou l'intensité lumineuse"],
  ["intermediate", "robotics", "motor", "H-Bridge", "le pont en H", "تغيير اتجاه دوران محرك DC", "changer le sens de rotation d'un moteur DC"],
  ["intermediate", "robotics", "sensor", "الحلقة المغلقة", "la boucle fermée", "تصحيح القرار باستعمال قياس راجع", "corriger la décision avec une mesure de retour"],
  ["intermediate", "robotics", "robot", "PID مبسط", "le PID simplifié", "تقليل الخطأ بين الهدف والقياس", "réduire l'erreur entre la cible et la mesure"],
  ["intermediate", "robotics", "sensor", "روبوت يتبع الخط", "le robot suiveur de ligne", "استعمال حساسات لاكتشاف مسار", "utiliser des capteurs pour suivre une piste"],
  ["intermediate", "robotics", "sensor", "Wheel Encoder", "l'encodeur de roue", "تقدير حركة العجلة أو المسافة", "estimer le mouvement de la roue ou la distance"],
  ["intermediate", "robotics", "robot", "I2C", "l'I2C", "تواصل عدة مكونات عبر أسلاك قليلة", "faire communiquer plusieurs composants avec peu de fils"],
  ["intermediate", "robotics", "robot", "إدارة الطاقة", "la gestion de l'énergie", "تجنب هبوط الجهد وتعطل الروبوت", "éviter les chutes de tension et les pannes"],
  ["advanced", "robotics", "sensor", "Sensor Fusion", "la fusion de capteurs", "دمج قياسات متعددة لقرار أدق", "combiner plusieurs mesures pour une décision plus précise"],
  ["advanced", "robotics", "robot", "SLAM", "le SLAM", "بناء خريطة وتحديد موقع الروبوت", "construire une carte et localiser le robot"],
  ["advanced", "robotics", "sensor", "Odometry", "l'odométrie", "تقدير الحركة من دوران العجلات", "estimer le déplacement à partir des roues"],
  ["advanced", "robotics", "robot", "Kinematics", "la cinématique", "ربط حركة المفاصل بحركة الجسم", "relier les mouvements des articulations au corps"],
  ["advanced", "robotics", "robot", "Path Planning", "la planification de trajectoire", "اختيار مسار آمن نحو الهدف", "choisir un chemin sûr vers l'objectif"],
  ["advanced", "robotics", "sensor", "Kalman Filter", "le filtre de Kalman", "تقليل الضجيج في القياسات", "réduire le bruit dans les mesures"],
  ["advanced", "robotics", "robot", "Real-time Control", "le contrôle temps réel", "اتخاذ القرار داخل زمن محدود", "prendre une décision dans un délai limité"],
  ["advanced", "robotics", "robot", "ROS", "ROS", "تنظيم برمجيات الروبوت في وحدات متواصلة", "organiser le logiciel robotique en modules communicants"],
  ["advanced", "robotics", "security", "Safety Interlock", "le verrouillage de sécurité", "إيقاف الروبوت عند خطر واضح", "arrêter le robot en cas de danger"],

  ["beginner", "cs", "code", "الخوارزمية", "l'algorithme", "حل مشكلة بخطوات مرتبة", "résoudre un problème par étapes ordonnées"],
  ["beginner", "cs", "code", "المتغير", "la variable", "حفظ قيمة لاستعمالها لاحقا", "stocker une valeur pour la réutiliser"],
  ["beginner", "cs", "code", "الحلقة Loop", "la boucle", "تكرار تعليمات عدة مرات", "répéter des instructions plusieurs fois"],
  ["beginner", "cs", "code", "الشرط", "la condition", "اختيار مسار حسب نتيجة اختبار", "choisir un chemin selon un test"],
  ["beginner", "cs", "code", "الدالة", "la fonction", "تنظيم الكود وإعادة استعماله", "organiser et réutiliser le code"],
  ["beginner", "cs", "code", "القائمة Array", "le tableau", "تخزين عدة قيم بترتيب", "stocker plusieurs valeurs dans l'ordre"],
  ["beginner", "cs", "web", "HTML", "HTML", "بناء هيكل صفحة الويب", "construire la structure d'une page web"],
  ["beginner", "cs", "web", "CSS", "CSS", "تنسيق شكل صفحة الويب", "mettre en forme une page web"],
  ["intermediate", "cs", "code", "Stack", "la pile", "تخزين عناصر بمبدأ آخر داخل أول خارج", "stocker des éléments en dernier entré premier sorti"],
  ["intermediate", "cs", "code", "Queue", "la file", "تخزين عناصر بمبدأ أول داخل أول خارج", "stocker des éléments en premier entré premier sorti"],
  ["intermediate", "cs", "code", "Binary Search", "la recherche binaire", "البحث بسرعة داخل قائمة مرتبة", "chercher rapidement dans une liste triée"],
  ["intermediate", "cs", "web", "API", "l'API", "ربط برنامج بخدمة أو برنامج آخر", "relier un programme à un service ou un autre programme"],
  ["intermediate", "cs", "web", "HTTP", "HTTP", "تبادل الطلبات والردود على الويب", "échanger des requêtes et réponses sur le web"],
  ["intermediate", "cs", "code", "JSON", "JSON", "تمثيل بيانات بشكل سهل التبادل", "représenter des données faciles à échanger"],
  ["intermediate", "cs", "code", "Debugging", "le débogage", "العثور على الأخطاء وإصلاحها", "trouver et corriger les erreurs"],
  ["intermediate", "cs", "code", "Git", "Git", "تتبع تغييرات المشروع البرمجي", "suivre les changements d'un projet logiciel"],
  ["advanced", "cs", "code", "Graph", "le graphe", "تمثيل علاقات بين عناصر كثيرة", "représenter des relations entre de nombreux éléments"],
  ["advanced", "cs", "code", "Recursion", "la récursion", "حل مسألة باستدعاء نفس الفكرة", "résoudre un problème en réutilisant la même idée"],
  ["advanced", "cs", "code", "Dynamic Programming", "la programmation dynamique", "تجنب إعادة حساب نفس النتائج", "éviter de recalculer les mêmes résultats"],
  ["advanced", "cs", "code", "Big O", "la notation Big O", "تقدير نمو زمن أو ذاكرة الخوارزمية", "estimer la croissance du temps ou de la mémoire"],
  ["advanced", "cs", "code", "Hash Table", "la table de hachage", "الوصول السريع إلى قيمة عبر مفتاح", "accéder vite à une valeur par clé"],
  ["advanced", "cs", "code", "Tree", "l'arbre", "تمثيل بيانات هرمية", "représenter des données hiérarchiques"],
  ["advanced", "cs", "code", "Concurrency", "la concurrence", "تنفيذ مهام متعددة بتنسيق", "exécuter plusieurs tâches de façon coordonnée"],
  ["advanced", "cs", "code", "Database Index", "l'index de base de données", "تسريع البحث داخل قاعدة بيانات", "accélérer la recherche dans une base de données"],
  ["advanced", "cs", "code", "اختبارات الوحدة", "les tests unitaires", "التحقق من أجزاء صغيرة من الكود", "vérifier de petites parties du code"],

  ["beginner", "tech", "tech", "CPU", "le CPU", "تنفيذ تعليمات البرامج", "exécuter les instructions des programmes"],
  ["beginner", "tech", "tech", "RAM", "la RAM", "حفظ بيانات مؤقتة أثناء العمل", "stocker temporairement des données pendant l'exécution"],
  ["beginner", "tech", "tech", "التخزين", "le stockage", "حفظ الملفات لمدة طويلة", "conserver les fichiers durablement"],
  ["beginner", "tech", "tech", "نظام التشغيل", "le système d'exploitation", "إدارة الجهاز والبرامج", "gérer l'appareil et les programmes"],
  ["beginner", "tech", "network", "الإنترنت", "Internet", "ربط أجهزة وخدمات عبر الشبكة", "relier des appareils et services par réseau"],
  ["beginner", "tech", "security", "كلمة المرور القوية", "le mot de passe fort", "حماية الحساب من التخمين السهل", "protéger un compte contre les devinettes simples"],
  ["beginner", "tech", "security", "التصيد الإلكتروني", "le phishing", "خداع المستخدم للحصول على معلوماته", "tromper l'utilisateur pour obtenir ses informations"],
  ["beginner", "tech", "network", "الخدمات السحابية", "les services cloud", "استعمال موارد عبر الإنترنت", "utiliser des ressources via Internet"],
  ["intermediate", "tech", "network", "DNS", "le DNS", "تحويل اسم الموقع إلى عنوان شبكة", "convertir un nom de site en adresse réseau"],
  ["intermediate", "tech", "network", "IP Address", "l'adresse IP", "تمييز جهاز أو خدمة داخل شبكة", "identifier un appareil ou service dans un réseau"],
  ["intermediate", "tech", "security", "HTTPS", "HTTPS", "تأمين تبادل البيانات مع الموقع", "sécuriser l'échange de données avec un site"],
  ["intermediate", "tech", "security", "2FA", "la double authentification", "إضافة خطوة تحقق ثانية للحساب", "ajouter une deuxième étape de vérification"],
  ["intermediate", "tech", "security", "Backup", "la sauvegarde", "استرجاع البيانات عند الفقدان", "récupérer les données en cas de perte"],
  ["intermediate", "tech", "tech", "Open Source", "l'open source", "إتاحة الكود للمراجعة والتطوير", "rendre le code disponible pour l'examen et l'amélioration"],
  ["intermediate", "tech", "tech", "Virtual Machine", "la machine virtuelle", "تشغيل نظام داخل بيئة افتراضية", "faire tourner un système dans un environnement virtuel"],
  ["intermediate", "tech", "tech", "Database", "la base de données", "تنظيم معلومات قابلة للبحث", "organiser des informations recherchables"],
  ["advanced", "tech", "security", "التشفير", "le chiffrement", "حماية البيانات بتحويلها لصيغة غير مفهومة", "protéger les données en les rendant illisibles"],
  ["advanced", "tech", "security", "Firewall", "le pare-feu", "فلترة حركة الشبكة حسب قواعد", "filtrer le trafic réseau selon des règles"],
  ["advanced", "tech", "tech", "Container", "le conteneur", "تشغيل تطبيق مع اعتمادياته في بيئة معزولة", "exécuter une application avec ses dépendances dans un environnement isolé"],
  ["advanced", "tech", "network", "Load Balancer", "le répartiteur de charge", "توزيع الطلبات على عدة خوادم", "répartir les requêtes entre plusieurs serveurs"],
  ["advanced", "tech", "tech", "CI/CD", "le CI/CD", "أتمتة اختبار ونشر البرمجيات", "automatiser les tests et le déploiement"],
  ["advanced", "tech", "network", "Monitoring", "la supervision", "مراقبة صحة الأنظمة والأداء", "surveiller la santé et la performance des systèmes"],
  ["advanced", "tech", "security", "Zero Trust", "le Zero Trust", "التحقق المستمر بدل الثقة التلقائية", "vérifier en continu au lieu de faire confiance automatiquement"],
  ["advanced", "tech", "security", "TLS", "TLS", "تأمين الاتصال بين العميل والخادم", "sécuriser la connexion entre client et serveur"],
  ["advanced", "tech", "security", "Incident Response", "la réponse à incident", "تقليل أثر حادث أمني واسترجاع العمل", "réduire l'impact d'un incident et rétablir le service"],
];

function makeExpansionSeed(rawSeed) {
  const [level, category, visual, arTopic, frTopic, arRole, frRole] = rawSeed;
  const context = categoryQuestionContext[category];
  return {
    level,
    category,
    visual,
    ar: {
      topic: arTopic,
      definition: `${arTopic} ${context.arConceptKind} يساعد على ${arRole}.`,
      useCase: `نستعمل ${arTopic} عندما نحتاج إلى ${arRole}.`,
      benefit: `يساعد ${arTopic} على إنجاز ${arRole} بدقة وتنظيم.`,
      misconception: `${arTopic} مجرد اسم تجاري ولا يؤثر على الحل.`,
      offTopic: context.arOffTopic,
    },
    fr: {
      topic: frTopic,
      definition: `${frTopic} est ${context.frConceptKind} qui aide à ${frRole}.`,
      useCase: `On utilise ${frTopic} quand on doit ${frRole}.`,
      benefit: `${frTopic} aide à ${frRole} avec plus de précision et d'organisation.`,
      misconception: `${frTopic} est seulement un nom commercial sans effet sur la solution.`,
      offTopic: context.frOffTopic,
    },
  };
}

function buildGeneratedQuestions(rawSeed, index) {
  const seed = makeExpansionSeed(rawSeed);
  const context = categoryQuestionContext[seed.category];
  const baseId = `x-${seed.level.slice(0, 1)}-${seed.category}-${String(index + 1).padStart(3, "0")}`;
  const common = {
    level: seed.level,
    category: seed.category,
    visual: seed.visual,
  };

  const definitionQuestion = {
    ...common,
    id: `${baseId}-def`,
    type: "choice",
    prompt: `ما أفضل وصف لـ ${seed.ar.topic}؟`,
    options: [seed.ar.definition, seed.ar.misconception, seed.ar.offTopic, "إيقاف الجهاز دون سبب"],
    answer: seed.ar.definition,
    explanation: seed.ar.definition,
    fr: {
      prompt: `Quelle est la meilleure description de ${seed.fr.topic} ?`,
      options: [seed.fr.definition, seed.fr.misconception, seed.fr.offTopic, "éteindre l'appareil sans raison"],
      explanation: seed.fr.definition,
    },
  };

  const useCaseQuestion = {
    ...common,
    id: `${baseId}-use`,
    type: "choice",
    prompt: `متى يكون استعمال ${seed.ar.topic} مناسبا؟`,
    options: [seed.ar.useCase, seed.ar.offTopic, seed.ar.misconception, "عندما نريد حذف كل الاختبارات"],
    answer: seed.ar.useCase,
    explanation: seed.ar.benefit,
    fr: {
      prompt: `Quand l'utilisation de ${seed.fr.topic} est-elle adaptée ?`,
      options: [seed.fr.useCase, seed.fr.offTopic, seed.fr.misconception, "quand on veut supprimer tous les tests"],
      explanation: seed.fr.benefit,
    },
  };

  const isTrue = index % 2 === 0;
  const booleanQuestion = {
    ...common,
    id: `${baseId}-tf`,
    type: "boolean",
    prompt: isTrue
      ? `${seed.ar.topic} يساعد في ${context.arDomain} لأنه يرتبط بـ ${rawSeed[5]}.`
      : `${seed.ar.topic} يرتبط فقط بـ ${seed.ar.offTopic}.`,
    answer: isTrue,
    explanation: isTrue ? seed.ar.benefit : `هذا غير صحيح؛ ${seed.ar.definition}`,
    fr: {
      prompt: isTrue
        ? `${seed.fr.topic} aide dans ${context.frDomain} car il est lié à ${rawSeed[6]}.`
        : `${seed.fr.topic} est lié uniquement à ${seed.fr.offTopic}.`,
      explanation: isTrue ? seed.fr.benefit : `Ce n'est pas correct ; ${seed.fr.definition}`,
    },
  };

  const extraType = index % 4;
  let interactiveQuestion;
  if (extraType === 0) {
    interactiveQuestion = {
      ...common,
      id: `${baseId}-match`,
      type: "match",
      prompt: `طابق عناصر ${seed.ar.topic} مع معناها الأقرب.`,
      pairs: [
        { left: seed.ar.topic, right: seed.ar.definition },
        { left: "حالة استعمال", right: seed.ar.useCase },
        { left: "الفائدة الأساسية", right: seed.ar.benefit },
      ],
      explanation: `المطابقة الصحيحة تبدأ من فهم الدور، ثم حالة الاستعمال، ثم الفائدة العملية.`,
      fr: {
        prompt: `Associe les éléments de ${seed.fr.topic} à leur sens le plus proche.`,
        pairs: [
          { left: seed.fr.topic, right: seed.fr.definition },
          { left: "Cas d'utilisation", right: seed.fr.useCase },
          { left: "Bénéfice principal", right: seed.fr.benefit },
        ],
        explanation: "La bonne association commence par le rôle, puis le cas d'usage, puis le bénéfice pratique.",
      },
    };
  } else if (extraType === 1) {
    interactiveQuestion = {
      ...common,
      id: `${baseId}-order`,
      type: "order",
      prompt: `رتب طريقة استعمال ${seed.ar.topic} في مشروع صغير.`,
      options: context.arWorkflow,
      correctOrder: context.arWorkflow,
      explanation: "العمل المنظم يبدأ بفهم المطلوب ثم التطبيق ثم الاختبار.",
      fr: {
        prompt: `Mets dans l'ordre l'utilisation de ${seed.fr.topic} dans un petit projet.`,
        options: context.frWorkflow,
        explanation: "Un travail organisé commence par le besoin, puis l'application, puis le test.",
      },
    };
  } else {
    interactiveQuestion = {
      ...common,
      id: `${baseId}-multi`,
      type: "multi",
      prompt: `اختر عبارتين صحيحتين حول ${seed.ar.topic}.`,
      options: [seed.ar.definition, seed.ar.benefit, seed.ar.misconception, seed.ar.offTopic],
      answers: [seed.ar.definition, seed.ar.benefit],
      explanation: `العبارتان الصحيحتان هما التي تصف الدور والفائدة العملية.`,
      fr: {
        prompt: `Choisis deux phrases correctes à propos de ${seed.fr.topic}.`,
        options: [seed.fr.definition, seed.fr.benefit, seed.fr.misconception, seed.fr.offTopic],
        explanation: "Les deux bonnes réponses décrivent le rôle et le bénéfice pratique.",
      },
    };
  }

  return [definitionQuestion, useCaseQuestion, booleanQuestion, interactiveQuestion];
}

const generatedQuestionExpansion = questionExpansionSeeds.flatMap(buildGeneratedQuestions).slice(0, 400);

export const questions = [...curatedQuestions, ...generatedQuestionExpansion];
